name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04  # Specify Ubuntu 22.04 explicitly

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4
      with:
        lfs: true  # Enable LFS support
        
    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    # Step 3: Build and tag the Docker image
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/airoha_env:latest
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/airoha_env:${{ github.sha }}

    # Step 4: Push the Docker image to GHCR
    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/airoha:latest
        docker push ghcr.io/${{ github.repository_owner }}/airoha:${{ github.sha }}